version: '3.7'
services:
  mongodb:
    image: mongo
    container_name: tcc_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
