name: Test & build the server & client
'on':
  push:
    branches:
      - main
  pull_request:

jobs:
  test_build_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run test -w server
      - run: npm run start -w server
      - run: npm run lint -w client
      - run: npm run build -w client
